[project]
name = "cvec"
version = "0.1.0"
description = ""
authors = [
    {name = "Joshua Napoli",email = "jnapoli@cvector.energy"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "cvec", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
